export const places = [
  {
    id: 1,
    title: 'Interior mina',
    subtitle: 'Interior mina Caravelina',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616938/Pukaqaqa/interior_sir2pj.jpg',
    x: 776,
    y: 372,
  },
  {
    id: 2,
    title: 'Interior mina',
    subtitle: 'Interior mina Caravelina',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616938/Pukaqaqa/interior1_xgvj0z.jpg',
    x: 762,
    y: 376,
  },
  {
    id: 3,
    title: 'Interior mina',
    subtitle: 'Interior mina Caravelina',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616938/Pukaqaqa/interior2_z9bomj.jpg',
    x: 746,
    y: 377,
  },
  {
    id: 4,
    title: 'Interior mina',
    subtitle: 'Interior mina Caravelina',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616938/Pukaqaqa/interior3_wcjvpr.jpg',
    x: 728,
    y: 380,
  },
  {
    id: 5,
    title: 'Bocamina',
    subtitle: 'Bocamina Caravelina',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616938/Pukaqaqa/bocamina_sxfcxk.jpg',
    x: 710,
    y: 382,
  },
  {
    id: 6,
    title: 'Ingreso a mina',
    subtitle: 'Ingreso a mina Caravelina',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616938/Pukaqaqa/ingreso_kybayv.jpg',
    x: 691,
    y: 383,
  },
  {
    id: 7,
    title: 'Oficina',
    subtitle: 'Oficina Ecohñan',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616939/Pukaqaqa/oficinas1_do7ypr.jpg',
    x: 655,
    y: 450,
  },
  {
    id: 8,
    title: 'Oficinas',
    subtitle: 'Oficinas Ecohñan',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616939/Pukaqaqa/oficinas_a7ezyi.jpg',
    x: 639,
    y: 455,
  },
  {
    id: 9,
    title: 'Campamento',
    subtitle: 'Campamento Ecohñan',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616939/Pukaqaqa/campamento_t3f6bw.jpg',
    x: 635,
    y: 468,
  },
  {
    id: 10,
    title: 'Comunicado',
    subtitle: 'Comunicado prohibición de tránsito',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616939/Pukaqaqa/comunicado_ux9d9l.jpg',
    x: 870,
    y: 503,
  },
  {
    id: 11,
    title: 'Vía cerrada',
    subtitle: 'Vía cerrada a labores de Ecohñan',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616940/Pukaqaqa/via_sg8xhp.jpg',
    x: 855,
    y: 498,
  },
  {
    id: 12,
    title: 'Letrero',
    subtitle: 'Vía cerrada',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658616939/Pukaqaqa/letrero_da84xc.jpg',
    x: 872,
    y: 482,
  },
];
